In [1]:
from datetime import datetime
import os
import pandas as pd
import pickle
import utils

In [2]:
time_id = datetime.today().strftime('%Y%m%d')
geckodriver_path = r'C:\Users\nicol\anaconda3\Library\bin\geckodriver'

print(f'\nSi es la primera vez que corre este programa, por favor abra la terminal PowerShell de Anaconda' +
      f' e ingrese el siguiente comando:\n\n\033[1mpip install -r {os.getcwd()}\\requirements.txt\033[0m\n')

Si es la primera vez que corre este programa, por favor abra la terminal PowerShell de Anaconda e ingrese el siguiente comando:

pip install -r C:\Users\nicol\Proyectos\GitHub\Ganter-Investment\requirements.txt

In [ ]:
username = str(input('Favor ingrese su usuario: ')) #FEN
password = str(input('Favor ingrese su contraseña: ')) #'WS2020'

browser = utils.login_investing(geckodriver_path, username, password)
country = 27

df_main = utils.get_inmutable(browser, country)
display(df_main)

In [5]:
df_main.to_pickle(f'{time_id}_tabla_inmutable_completa.pickle')
df_main.to_excel(f'{time_id}_tabla_inmutable_completa.xlsx')

In [19]:
import time
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait

investing_url = 'https://www.investing.com'

for row in range(df_main.shape[0]):
    browser.get(f'{investing_url}{df_main.at[row, "url"]}-historical-data')
    time.sleep(0.5)

    WebDriverWait(browser, 5).until(EC.presence_of_element_located((By.ID, 'widgetFieldDateRange'))).click()
    date_input = browser.find_element_by_id('startDate')

    WebDriverWait(browser, 5).until(EC.presence_of_element_located((By.ID, 'startDate'))).clear()
    date_input.send_keys('01/01/1990')

    WebDriverWait(browser, 5).until(EC.element_to_be_clickable((By.CSS_SELECTOR, '#applyBtn'))).click()
    time.sleep(3)
    
    df_list = pd.read_html(browser.page_source, attrs={'class':'genTbl closedTbl historicalTbl',
                                                       'id':'curr_table'}, keep_default_na=False)
    df_stock = pd.concat(df_list)
    break
    
display(df_stock)

              Date    Price     Open     High      Low     Vol. Change %
0     Oct 14, 2013  7223.80  7137.00  7240.00  7137.00  386.05K    0.22%
1     Oct 11, 2013  7208.30  7147.50  7230.00  7120.00  245.50K    0.85%
2     Oct 10, 2013  7147.50  7000.00  7178.00  7000.00  339.94K    2.37%
3     Oct 09, 2013  6982.30  7141.00  7141.00  6950.00  419.05K   -1.75%
4     Oct 08, 2013  7106.50  7063.50  7134.10  7050.00  309.34K    0.61%
...            ...      ...      ...      ...      ...      ...      ...
4994  Oct 04, 1993   740.01   734.29   740.01   734.29        -    0.78%
4995  Oct 01, 1993   734.29   726.66   734.29   726.66        -    1.05%
4996  Sep 30, 1993   726.66   726.66   726.66   726.66        -    0.00%
4997  Sep 29, 1993   726.66   726.66   726.66   726.66        -    0.00%
4998  Sep 28, 1993   726.66   726.66   726.66   726.66        -    0.00%

[4999 rows x 7 columns]

In [22]:
type(df_stock.at[0, 'Change %'])

str